// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LendSellController from "./lend_sell_controller"
application.register("lend-sell", LendSellController)

import ClearFilesController from "./clear_files_controller"
application.register("clear-files", ClearFilesController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ImageSwitchController from "./image_switch_controller"
application.register("image-switch", ImageSwitchController)

import DropdownToggleController from "./dropdown_toggle_controller"
application.register("dropdown-toggle", DropdownToggleController)
